/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

const Clouds = (props: GroupProps) => {
    
    // @ts-ignore
    const { nodes, materials } = useGLTF("/models/Clouds.glb");
    
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Node.geometry}
                material={materials.mat21}
            />
        </group>
    );
}

useGLTF.preload("/models/Clouds.glb");

export default Clouds;