/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import * as THREE from 'three';

const Cloud = (props: GroupProps) => {
    // @ts-ignore
    const { nodes, materials } = useGLTF("/models/Cloud.glb");
    
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cloud1.geometry}
                material={new THREE.MeshStandardMaterial({ color: '#fafafa' })}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
        </group>
    );
}

useGLTF.preload("/models/Cloud.glb");

export default Cloud;
