/*
Auto-generated by: https://github.com/pmndrs/gltfjsx

// Island by J-Toastie [CC-BY] via Poly Pizza
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

const Island = (props: GroupProps) => {
    // @ts-ignore
    const { nodes, materials } = useGLTF("/models/Island.glb");
    
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Island01_Cylinder-Mesh"].geometry}
                material={materials.Dirt}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Island01_Cylinder-Mesh_1"].geometry}
                material={materials.Grass}
            />
        </group>
    );
}

useGLTF.preload("/models/Island.glb");

export default Island;
